name: pqr
channels:
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - python=3.8 #nmslib in pyserini only works python <= 3.9
  - pip
  - ftfy
  - faiss-gpu #faiss-cpu is also an option
  - rich
  - pandas
  - pip:
      - pyserini==0.19.1
      - pytrec-eval-terrier==0.5.5
      - t5 #also use our fork