name: repair
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 #nmslib in pyserini only works python <= 3.9
  - pip
  - pytorch
  - ftfy
  - rich
  - pandas
  - pip:
      - ir_datasets
      - pyserini==0.19.1
      - t5
      - filesplit