name: pqr
channels:
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - python=3.8 #nmslib in pyserini only works python <= 3.9
  - pip
  - ftfy
  - faiss-gpu
  - rich
  - pip:
      - pyserini

