# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
blis                      0.7.8                    pypi_0    pypi
ca-certificates           2022.07.19           haa95532_0  
catalogue                 2.0.8                    pypi_0    pypi
certifi                   2022.6.15        py38haa95532_0  
charset-normalizer        2.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.5                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
cymem                     2.0.6                    pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
faiss                     1.7.2                    pypi_0    pypi
faiss-cpu                 1.7.2           py3.8_h2272212_0_cpu    pytorch
filelock                  3.8.0                    pypi_0    pypi
flatbuffers               2.0                      pypi_0    pypi
huggingface-hub           0.8.1                    pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
idna                      3.3                      pypi_0    pypi
intel-openmp              2022.0.0          haa95532_3663  
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
langcodes                 3.3.0                    pypi_0    pypi
libfaiss                  1.7.2            h2e52968_0_cpu    pytorch
lightgbm                  3.3.2                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
mkl                       2020.2                      256  
mkl-service               2.3.0            py38h196d8e1_0  
mkl_fft                   1.3.0            py38h46781fe_0  
mkl_random                1.1.1            py38h47e9c7a_0  
mpmath                    1.2.1                    pypi_0    pypi
murmurhash                1.0.8                    pypi_0    pypi
nmslib                    2.1.1                    pypi_0    pypi
numpy                     1.23.2                   pypi_0    pypi
numpy-base                1.19.2           py38ha3acd2a_0  
onnxruntime               1.12.1                   pypi_0    pypi
openjdk                   11.0.15              h57928b3_1    conda-forge
openssl                   1.1.1q               h2bbff1b_0  
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.3                    pypi_0    pypi
pathy                     0.6.2                    pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pip                       22.1.2           py38haa95532_0  
preshed                   3.0.7                    pypi_0    pypi
protobuf                  4.21.5                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
pybind11                  2.6.1                    pypi_0    pypi
pydantic                  1.9.2                    pypi_0    pypi
pyjnius                   1.4.2                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyreadline3               3.4.1                    pypi_0    pypi
pyserini                  0.17.1                   pypi_0    pypi
python                    3.8.13               h6244533_0  
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.2.1                 pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
regex                     2022.8.17                pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.0                    pypi_0    pypi
sentencepiece             0.1.97                   pypi_0    pypi
setuptools                61.2.0           py38haa95532_0  
six                       1.16.0             pyhd3eb1b0_1  
smart-open                5.2.1                    pypi_0    pypi
spacy                     3.4.1                    pypi_0    pypi
spacy-legacy              3.0.10                   pypi_0    pypi
spacy-loggers             1.0.3                    pypi_0    pypi
sqlite                    3.39.2               h2bbff1b_0  
srsly                     2.4.4                    pypi_0    pypi
sympy                     1.10.1                   pypi_0    pypi
thinc                     8.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tokenizers                0.12.1                   pypi_0    pypi
torch                     1.8.1+cu111              pypi_0    pypi
torchaudio                0.8.1                    pypi_0    pypi
torchvision               0.9.1+cu111              pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
transformers              4.21.1                   pypi_0    pypi
typer                     0.4.2                    pypi_0    pypi
typing-extensions         4.3.0                    pypi_0    pypi
urllib3                   1.26.11                  pypi_0    pypi
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
wasabi                    0.10.1                   pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
wincertstore              0.2              py38haa95532_2  
